# Files for typos
# Instruction:  https://github.com/marketplace/actions/typos-action#getting-started

[default.extend-identifiers]

[default.extend-words]
ba="ba" # 7zコマンドの-baオプション
fo="fo" # powershellのrm -Forceの短縮

[files]
extend-exclude = ["pnpm-lock.yaml", "src/store/project.ts", "*.svg"]
