managePackageManagerVersions: true

minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - "@vizejs/*"
  - "@typescript/*"
  - vize

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@openapitools/openapi-generator-cli'
  - esbuild
  - vue-demi
