name: Test

on:
  push:
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

env:
  VOICEVOX_ENGINE_VERSION: 0.14.4

jobs:
  build-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/setup-environment
      # - run: npm run electron:build_pnever

      - name: Setup keystore
        shell: bash
        run: |
          cat - | base64 -d > keystore.jks <<EOF
          ${{ secrets.ANDROID_KEYSTORE_DATA }}
          EOF
          if [ -s keystore.jks ]; then
            echo "Created keystore.jks"
            SHA256=$(sha256sum keystore.jks | cut -d ' ' -f 1)
            echo "SHA256: $SHA256"
          else
            echo "Failed to create keystore.jks"
            echo "Have you set ANDROID_KEYSTORE_DATA, ANDROID_KEYSTORE_PASS, ANDROID_KEYSTORE_ALIAS and ANDROID_KEYSTORE_ALIAS_PASS?"
            exit 1
          fi
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'oracle'
      - name: Cache Android SDK
        id: cache-android-sdk
        uses: actions/cache@v3
        with:
          paths: |
           C:/Android/android-sdk
          key: v1
      - name: Setup Android SDK
        if: steps.cache-android-sdk.outputs.cache-hit != 'true'
        uses: android-actions/setup-android@v2
      - name: Download header file
        shell: bash
        run: |
          # FIXME: ちゃんとしたところ（Releasesで公開するようにする？）から落とすようにする
          curl -sSL https://cdn.discordapp.com/attachments/1000018124965417040/1102892919565856829/voicevox_core.h \
            -o ./android/app/src/main/jniLibs/include/voicevox_core.h
      - name: Build Android
        shell: bash
        run: |
          npm run cap:build:android -- \
            --keystorepath keystore.jks \
            --keystorepass ${{ secrets.ANDROID_KEYSTORE_PASS }} \
            --keystorealias ${{ secrets.ANDROID_KEYSTORE_ALIAS }} \
            --keystorealiaspass ${{ secrets.ANDROID_KEYSTORE_ALIAS_PASS }}

  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - run: npm run test:unit

      - name: Download VOICEVOX ENGINE
        id: download-engine
        uses: ./.github/actions/download-engine
        with:
          version: ${{ env.VOICEVOX_ENGINE_VERSION }}
          dest: ${{ github.workspace }}/voicevox_engine

      - name: Run npm run test:e2e
        shell: bash
        run: |
          cp .env.test .env
          sed -i -e 's|"../voicevox_engine/run.exe"|"${{ steps.download-engine.outputs.run_path }}"|' .env
          if [ -n "${{ runner.debug }}" ]; then
            DEBUG=pw:browser* npm run test:e2e
          else
            npm run test:e2e
          fi

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Disallowed licenses check
        run: npm run license:generate -- -o voicevox_licenses.json

      - run: npm run typecheck
      - run: npm run lint
      - run: npm run markdownlint
