name: Test for mobile

on:
  push:
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

env:
  VOICEVOX_ENGINE_VERSION: 0.14.4

defaults:
  run:
    shell: bash

jobs:
  android-check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Sync capacitor
        run: |
          npm run cap:sync

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: 20
          distribution: "oracle"
          cache: gradle

      # checkだとActionsがフリーズするので、lintを実行する
      - name: Run lint
        working-directory: android
        run: ./gradlew lint
